apiVersion: v1
kind: Service
metadata:
  name: python-devops-service
spec:
  selector:
    app: python-devops
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
