apiVersion: v1
kind: Service
metadata:
  name: python-devops-service
  namespace: python-devops-e2e
<<<<<<< HEAD
  labels:
    app: python-devops-e2e
spec:
  selector:
    app: python-devops-e2e
  type: NodePort
=======
spec:
  selector:
    app: python-devops-e2e
>>>>>>> 9199726 (Add Kubernetes namespace and update deployment and service)
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

